name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker pull directus/directus
          docker build -t raigorobin/viimanekatse --build-arg KEY=${{ secrets.DIRECTUS_KEY }} .

      - name: Push Docker image
        run: docker push raigorobin/viimanekatse
