name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build Directus
        run: npm run build

      - name: Set up Docker
        uses: azure/docker-login@v1
        with:
          login-server: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t raigorobin/viimanekatse .

      - name: Push Docker image
        run: docker push raigorobin/viimanekatse

      - name: Deploy to Docker
        uses: azure/docker@v1
        with:
          image: raigorobin/viimaekatse
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          tags: latest
