name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: testregistryraigo.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Pull Directus Docker image
        run: docker pull directus/directus:latest

      - name: Tag Docker image
        run: docker tag directus/directus:latest testregistryraigo.azurecr.io/my-directus-app:${{ github.sha }}

      - name: Push Docker image to Azure Container Registry
        run: docker push testregistryraigo.azurecr.io/my-directus-app:${{ github.sha }}

      - name: Initialize Directus
        run: |
          docker run -d \
            -p 8080:8080 \
            -e DATABASE_CLIENT=mysql \
            -e DATABASE_HOST=database \
            -e DATABASE_PORT=3306 \
            -e DATABASE_NAME=directus \
            -e DATABASE_USER=directus \
            -e DATABASE_PASSWORD=directus \
            -e DIRECTUS_ADMIN_EMAIL=admin@example.com \
            -e DIRECTUS_ADMIN_PASSWORD=4g58D05NAMzU \
            -e KEY=${{ secrets.DIRECTUS_KEY }} \
            --name=directus \
            directus/directus
