name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Pull Directus Docker image
        run: docker pull directus/directus:latest

      - name: Tag Docker image
        run: docker tag directus/directus:latest raigorobin/my-directus-app:${{ github.sha }}

      - name: Push Docker image to Docker Hub
        run: docker push raigorobin/my-directus-app:${{ github.sha }}
