name: Deploy Directus

on:
  push:
    branches:
      - main  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Pull Directus image
      run: docker pull directus/directus

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Add entrypoint script
      run: |
        echo "#!/bin/sh" > run.sh
        echo "directus start" >> run.sh
        echo "node index.js" >> run.sh

    - name: Build and push image
      run: |
        docker build -t ${{ secrets.DOCKER_USER }}/directus:latest .
        docker push ${{ secrets.DOCKER_USER }}/directus:latest

    - name: Deploy container
      env:
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      run: | 
        docker run -d --env-file .env ${{ secrets.DOCKER_USER }}/directus:latest /run.sh
