name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Pull Directus Docker image
        run: docker pull directus/directus:latest

      - name: Tag Docker image
        run: docker tag directus/directus:latest raigorobin/directus-app:${{ github.sha }}

      - name: Push Docker image
        run: docker push raigorobin/directus-app:${{ github.sha }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: testregistryraigo.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Push Docker image to Azure Container Registry
        run: docker push your-azure-container-registry-url/my-directus-app:${{ github.sha }}
