on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Directus Docker image
        run: docker pull directus/directus

      - name: Set up Docker Hub credentials
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login --username "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Tag and Push Docker image
        run: |
          docker tag directus/directus "${{ secrets.DOCKER_HUB_USERNAME }}/viimanekatse:latest"
          docker push "${{ secrets.DOCKER_HUB_USERNAME }}/viimanekatse:latest"

      - name: Create and populate environment file
        run: |
          echo "DATABASE_HOST=raigomysqlserver.mysql.database.azure.com" >> .env
          echo "DATABASE_PORT=3306" >> .env
          echo "DATABASE_NAME=raigomysqlserver" >> .env
          echo "DATABASE_USER=adminraigo" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: Install Sentry Node SDK
        run: npm install --save @sentry/node

      - name: Configure and run Directus container with Sentry
        run: |
          echo "const Sentry = require('@sentry/node');" >> server.js
          echo "Sentry.init({dsn: 'https://255cf149c69d405da08760c17416a5e6@o4505507285237760.ingest.sentry.io/4505507292315648', tracesSampleRate: 1.0});" >> server.js
          echo "" >> server.js
          echo "const transaction = Sentry.startTransaction({op: 'test', name: 'My First Test Transaction'});" >> server.js
          echo "" >> server.js
          echo "setTimeout(() => {" >> server.js
          echo "  try {" >> server.js
          echo "    foo();" >> server.js
          echo "  } catch (e) {" >> server.js
          echo "    Sentry.captureException(e);" >> server.js
          echo "  } finally {" >> server.js
          echo "    transaction.finish();" >> server.js
          echo "  }" >> server.js
          echo "}, 99);" >> server.js

          docker run -d --env-file .env -p 80:80 -v $(pwd)/server.js:/usr/src/app/server.js "${{ secrets.DOCKER_HUB_USERNAME }}/viimanekatse:latest"
