name: Pull and Push Directus Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Directus Docker image
        run: docker pull directus/directus

      - name: Set up Docker Hub credentials
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login --username "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Tag and Push Docker image
        run: |
          docker tag directus/directus "${{ secrets.DOCKER_HUB_USERNAME }}/viimanekatse:latest"
          docker push "${{ secrets.DOCKER_HUB_USERNAME }}/viimanekatse:latest"

      - name: Set up Directus environment variables
        run: |
          echo "KEY=${{ secrets.DIRECTUS_KEY }}" >> .env

      - name: Run Directus container
        run: docker run -d --env-file .env -p 80:80 "${{ secrets.DOCKER_HUB_USERNAME }}/viimanekatse:latest"

      - name: Open ports 80 and 8055
        run: |
          sudo ufw allow 80
          sudo ufw allow 8055
