name: Directus
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Directus Docker image
        run: docker pull directus/directus

      - name: Set up Docker Hub credentials
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login --username "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Tag and Push Docker image
        run: |
          docker tag directus/directus "${{ secrets.DOCKER_HUB_USERNAME }}/viimanekatse:latest"
          docker push "${{ secrets.DOCKER_HUB_USERNAME }}/viimanekatse:latest"

      - name: Create and populate environment file
        run: |
          echo "DATABASE_HOST=raigomysqlserver.mysql.database.azure.com" >> .env
          echo "DATABASE_PORT=3306" >> .env
          echo "DATABASE_NAME=raigomysqlserver" >> .env
          echo "DATABASE_USER=adminraigo" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: Install Sentry Node SDK
        run: |
          yarn add @sentry/node
          # or: npm install --save @sentry/node

      - name: Modify Sentry code
        run: |
          echo "const Sentry = require(\"@sentry/node\");" >> index.js
          echo "Sentry.init({" >> index.js
          echo '  dsn: "https://255cf149c69d405da08760c17416a5e6@o4505507285237760.ingest.sentry.io/4505507292315648",' >> index.js
          echo "  tracesSampleRate: 1.0," >> index.js
          echo "});" >> index.js

      - name: Run Directus container
        run: docker run -d --env-file .env -p 80:80 -p 9000:9000 -p 9001:9001 -p 3306:3306 "${{ secrets.DOCKER_HUB_USERNAME }}/viimanekatse:latest"
