name: Directus

on: 
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2

    - name: Pull Directus Docker image
      run: docker pull directus/directus

    - name: Set up Docker Hub credentials 
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Add entrypoint  
      run: |
        echo "#!/bin/sh" > run.sh
        echo "directus start" >> run.sh
        echo "node index.js" >> run.sh

    - name: Tag and Push Docker image
      run: |
        docker tag directus/directus ${{ secrets.DOCKER_HUB_USERNAME }}/directus:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/directus:latest

    - name: Create and populate environment file
      run: |
        echo DATABASE_HOST=${{ secrets.MYSQL_HOST }} >> .env
        echo DATABASE_PORT=3306 >> .env
        echo DATABASE_NAME=${{ secrets.MYSQL_DB }} >> .env
        echo DATABASE_USER=${{ secrets.MYSQL_USER }} >> .env
        echo DATABASE_PASSWORD=${{ secrets.MYSQL_PASSWORD }} >> .env
        echo DATABASE_SSL=true >> .env

    - name: Install Sentry Node SDK
      run: yarn add @sentry/node

    - name: Configure Sentry
      run: |
        echo "require('dotenv').config()" >> index.js
        echo "const Sentry = require('@sentry/node');" >> index.js
        echo "Sentry.init({" >> index.js 
        echo "  dsn: '${{ secrets.SENTRY_DSN }}'," >> index.js
        echo "});" >> index.js
        echo "process.on('unhandledRejection', err => {" >> index.js
        echo "  Sentry.captureException(err);" >> index.js
        echo "});" >> index.js

    - name: Run Directus container
      env:
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}
      run: |
        docker run -d --env-file .env ${{ secrets.DOCKER_HUB_USERNAME }}/directus:latest /run.sh
