name: Pull and Push Directus Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Directus Docker image
        run: docker pull directus/directus

      - name: Tag and Push Docker image
        run: |
          docker tag directus/directus raigorobin/viimanekatse:latest
          docker push raigorobin/viimanekatse:latest

      - name: Open ports 80 and 8055
        run: |
          sudo ufw allow 80
          sudo ufw allow 8055
