on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Directus Docker image
        run: docker pull directus/directus

      - name: Set up Docker Hub credentials
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login --username "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Tag and Push Docker image
        run: |
          docker tag directus/directus "${{ secrets.DOCKER_HUB_USERNAME }}/viimanekatse:latest"
          docker push "${{ secrets.DOCKER_HUB_USERNAME }}/viimanekatse:latest"

      - name: Create and populate environment file
        run: |
          echo "DATABASE_HOST=raigomysqlserver.mysql.database.azure.com" >> .env
          echo "DATABASE_PORT=3306" >> .env
          echo "DATABASE_NAME=raigomysqlserver" >> .env
          echo "DATABASE_USER=adminraigo" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: Run Directus container
        run: docker run -d --env-file .env -p 80:80 "${{ secrets.DOCKER_HUB_USERNAME }}/viimanekatse:latest"
